{% set name = "yaval" %}
{% set version = "0.0.1.post1" %}
{% set sha256 = "01268502ee76e472f0588d3ce77f6e1406eb99a9faabd4e16e18961cb5e2d39d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #fn: {{ name }}-{{ version }}.tar.gz
  #url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  #sha256: {{ sha256 }}
  path: ..

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib
    - vispy
    - pyside2

test:
  imports:
    - yaval

about:
  home: https://github.com/csachs/yaval
  license: BSD-2-Clause
  license_family: BSD
  summary: 'yet another visualization abstraction layer'
  description: |
    yet another visualization abstraction layer
  doc_url: https://github.com/csachs/yaval
  dev_url: https://github.com/csachs/yaval

extra:
  recipe-maintainers:
    - csachs
